export const types = {
  SET_USERNAME: 'SET_USERNAME',
  REMOVE_ALL_DESKS: 'REMOVE_ALL_DESKS',
  ADD_NEW_DESK: 'ADD_NEW_DESK',
  REMOVE_DESK: 'REMOVE_DESK',
  ADD_NEW_DESK_NAME: 'ADD_NEW_DESK_NAME',
  ADD_NEW_TASK: 'ADD_NEW_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  ADD_NEW_TASK_NAME: 'ADD_NEW_TASK_NAME',
  ADD_TASK_DESCRIPTION: 'ADD_TASK_DESCRIPTION',
  ADD_NEW_COMMENT: 'ADD_NEW_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  ADD_NEW_COMMENT_TEXT: 'ADD_NEW_COMMENT_TEXT',
};
